### ISSUE TITLE
Definizione dell'architettura del microservizio-anagrafe

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/specifica-architetturale#11]
Definizione architetturale del microservizio anagrafe

**Comment by alessandro-massarenti** [comment]
@casYy Ho mergiato in questo branch l'immagine dell'uml dell'anagrafe che hai caricato.

Domani scrivo la documentazione. Se vanno fatte altre modifiche facciamole in questo branch qui.

Se ti vengono in mente cose che hai fatto buttale pure giù nel documento oppure qui.

**Comment by alessandro-massarenti** [comment]
@casYy Riusciresti ad espandere le sezioni di Modello View e Viewmodel che poi le sistemo? grazie

**Comment by alessandro-massarenti** [comment]
@casYy Sei riuscito ad aggiungere le sezioni?

**Comment by SamuelPeron** [comment]
ti caricato le immagini relative alla issue #18 e la chiudo perchè risolta

**Comment by SamuelPeron** [comment]
oggi abbiado fatto una prima draft, domani completiamo e creiamo la PR @bonni1207 preparati
