### ISSUE TITLE
Definizione ad alto livello sistema di logging

### ISSUE THREAD

**Issue by SamuelPeron** [SWEasabi/specifica-architetturale#19]

**Comment by casYy** [comment]
@alessandro-massarenti 

Core: facade per il readerservice

ReaderService: local/database, local per i test, databasereaderservice usa la repository per fare operazioni sul db

Entità:
Log (generato da logrepository quando fa operazioni sul database)

Repository: 
LogRepository (interfaccia repository jpa, fa le operazioni sul database)
JsonBuilderService (costruisce json/map a partire dai log)

Classi di configurazione:
Config: Genera i bean che servono alle altre classi
Controller: gestisce gli endpoint

**Comment by alessandro-massarenti** [comment]
ok, @bonni1207 c'è l'immagine nel branch relativo al logging?

**Comment by bonni1207** [comment]
C'è ma devo aggiornarla

**Comment by alessandro-massarenti** [comment]
> C'è ma devo aggiornarla

Hai aggiornato l'immagine/immagini?

**Comment by alessandro-massarenti** [comment]
> Controller(REST): gestisce gli endpoint

@casYy Poi dovresti controllarmi la lista degli endpoint

**Comment by alessandro-massarenti** [comment]
@casYy Ho scritto tutto quello che mi sembra tu abbia fatto, dovresti darci una corretta e dirmi la lista degli endpoint, poi la sezione è completa.

**Comment by alessandro-massarenti** [comment]
@casYy , @bonni1207 come nota ti direi che le classi non rispettano troppo una logica di nomenclatura. Non è chiarissimo dai nomi cosa queste facciano e come si relazionano a livello di componenti generali.
