### ISSUE TITLE
Definizione ad alto livello specifica delle basi di dati

### ISSUE THREAD

**Issue by romano001** [SWEasabi/specifica-architetturale#22]
Abstract, analisi dei requisiti, progettazione concettuale, progettazione logica, indicizzazione.
@alessandro-massarenti cosa ne pensi?

**Comment by alessandro-massarenti** [comment]
Sempre contandolo nell'appendice del documento di specifica architetturale?

In generale ti direi di si 👍🏻👍🏻

**Comment by romano001** [comment]
Intanto lo facciamo nel repository a parte, comunque sì metteremo tutto come appendice della specifica architetturale

**Comment by romano001** [comment]
PR #26 ha steso la struttura generale di come il documento va redatto in modalità appendice
