### ISSUE TITLE
Riduzione immagini specifica basi dati

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/specifica-architetturale#31]
Alcune immagini sono enormi nel documento, si possono rendere più piccole.
Questa issue fa riferimento all'issue #22

**Comment by romano001** [comment]
Aspetto che Michele sistemi i nomi così inserisco direttamente quelle giuste

**Comment by romano001** [comment]
PR #30 riduce le dimensioni delle immagini nel documento
