### ISSUE TITLE
Sistemare lampione nel sistema di anagrafe

### ISSUE THREAD

**Issue by bonni1207** [SWEasabi/specifica-architetturale#32]
La tabella del lampione nel db dell'anagrafe non ha più la luminosità che è stata messa nel sistema di illuminazione/coordinazione
Quindi va sostituita con il wattaggio, sia nel documento che nel codice (vedi schema logico)

**Comment by romano001** [comment]
@bonni1207 questa issue è chiudibile? Ho controllato e il db del sistema di Anagrafica sembra essere a posto

**Comment by alessandro-massarenti** [comment]
@bonni1207 ma che schema logico? nel documento rilasciato vedo questo:

![image](https://github.com/SWEasabi/specifica-architetturale/assets/48263116/fea4c22a-0deb-480f-a519-396ef1819ffa)

![image](https://github.com/SWEasabi/specifica-architetturale/assets/48263116/e6ec7eb3-e27d-4880-944c-1e669e074f54)


![image](https://github.com/SWEasabi/specifica-architetturale/assets/48263116/5244a6a5-d24a-4526-af13-cdb154d19ff5)

Cosa va fatto quindi?

**Comment by casYy** [comment]
nulla, è apposto

**Comment by casYy** [comment]
il
