### ISSUE TITLE
Definizione ad alto livello sistema coordinazione/illuminazione

### ISSUE THREAD

**Issue by romano001** [SWEasabi/specifica-architetturale#6]
Pattern architetturali da usare, perché usarli, scopi

**Comment by alessandro-massarenti** [comment]
Si, @casYy , @bonni1207 questo è il sistema di gestione e il sistema di gestione illuminazione.

**Comment by bonni1207** [comment]
![schema gestione-illuminazione](https://github.com/SWEasabi/specifica-architetturale/assets/44138357/377267d4-1d64-4a21-85b4-b9c1b0f508e6)

**Comment by alessandro-massarenti** [comment]
> ![schema gestione-illuminazione](https://user-images.githubusercontent.com/44138357/255276487-377267d4-1d64-4a21-85b4-b9c1b0f508e6.png)

@pierobonluca01 dacci un occhio

**Comment by alessandro-massarenti** [comment]
@bonni1207 Ho aggiunto una prima draft. Estendi la sezione relativa ai servizi, al core e alle cose. Poi la sistemo

**Comment by alessandro-massarenti** [comment]
@bonni1207 @casYy avete aggiornamenti?

**Comment by casYy** [comment]
> @bonni1207 @casYy avete aggiornamenti?

Classi sistema di illuminazione:

Controller: solita roba, riceve gli endpoint

Entità:
AreaAnagrafica
LampAnagrafica
Misuratore
SensoreAnagrafica

tutti oggetti costruiti dalle tabelle del db tramite jpa

Repository:
AreaRepository
LampRepository
MisuratoreRepository
SensoreRepository

solita roba, fanno operazioni sul db tramite jpa

Configurazione:
beanconfig: ha un botto di bean per configurare tutta la parte di mqtt e di scrittura in database

Parte Mqtt:
MqttController: è il centro che contiene consumer/producer
Producer: quando ha una rilevazione dal topic sensore lo segnala al logging (che sarà poi iscritto al topic logging e creerà i suoi log), poi fa partire un payload (che è un thread) e lo aggiunge nella coda dei payload
Consumer: quando vede che la coda non è vuota raccoglie le operazioni da fare, chiama la funzione che modifica la luminosità sul db e scrive ai lampioni via mqtt di modificare le proprie luminosità

Payloads: 
Payload (interfaccia)
PayloadQueue(coda di payload)
PayloadThread (
PayloadStatus: è un enum che contiene i possibili stati dei payload
manualpayload: generato per richieste manuali
autopayload: generato per richieste automatiche

manual e auto sono thread che fanno le loro operazioni in parallelo (controllano se c'è da modificare e in caso lo caricano in una variabile che poi il consumer va a mangiare)

Logica database:
CoreIlluminazione: usa le repo per fare operazioni sul db (si accettano suggerimenti per cambiargli nome, potrebbe essere WriterService, non saprei)

**Comment by alessandro-massarenti** [comment]
@bonni1207 Riesci a fare le immagini? le hai già caricate?

**Comment by bonni1207** [comment]
Le faccio dopo pranzo

**Comment by alessandro-massarenti** [comment]
@bonni1207 Mi mancano solo le tue immagini e poi si può fare la PR
